CREATE TABLE public."RESERVATION_STATUSES"
(
    "ID" integer PRIMARY KEY NOT NULL,
    "NAME" varchar(15)
);
INSERT INTO public."RESERVATION_STATUSES" ("ID", "NAME") VALUES (4, 'CANCELLED');
INSERT INTO public."RESERVATION_STATUSES" ("ID", "NAME") VALUES (2, 'CONFIRMED');